/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Account = IDL.Record({
  'pnl' : IDL.Float64,
  'totalPortfolioValue' : IDL.Float64,
  'lastUpdated' : Time,
  'icpBalance' : IDL.Float64,
  'cashBalance' : IDL.Float64,
  'principalId' : IDL.Principal,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const LedgerTransaction = IDL.Record({
  'transactionType' : TransactionType,
  'icpBalanceAfter' : IDL.Float64,
  'timestamp' : Time,
  'price' : IDL.Float64,
  'cashBalanceAfter' : IDL.Float64,
  'icpAmount' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyICP' : IDL.Func([IDL.Float64], [], []),
  'getBalance' : IDL.Func([], [IDL.Text, IDL.Float64, IDL.Float64], []),
  'getBalanceForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Text, IDL.Float64, IDL.Float64],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getICPPrice' : IDL.Func([], [IDL.Float64], []),
  'getOrCreateAccount' : IDL.Func([], [Account], []),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(LedgerTransaction)],
      ['query'],
    ),
  'getTransactionHistoryForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LedgerTransaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDefaultGameMode' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellICP' : IDL.Func([IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Account = IDL.Record({
    'pnl' : IDL.Float64,
    'totalPortfolioValue' : IDL.Float64,
    'lastUpdated' : Time,
    'icpBalance' : IDL.Float64,
    'cashBalance' : IDL.Float64,
    'principalId' : IDL.Principal,
  });
  const TransactionType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const LedgerTransaction = IDL.Record({
    'transactionType' : TransactionType,
    'icpBalanceAfter' : IDL.Float64,
    'timestamp' : Time,
    'price' : IDL.Float64,
    'cashBalanceAfter' : IDL.Float64,
    'icpAmount' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyICP' : IDL.Func([IDL.Float64], [], []),
    'getBalance' : IDL.Func([], [IDL.Text, IDL.Float64, IDL.Float64], []),
    'getBalanceForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Text, IDL.Float64, IDL.Float64],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getICPPrice' : IDL.Func([], [IDL.Float64], []),
    'getOrCreateAccount' : IDL.Func([], [Account], []),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(LedgerTransaction)],
        ['query'],
      ),
    'getTransactionHistoryForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LedgerTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDefaultGameMode' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellICP' : IDL.Func([IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };