/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Time = IDL.Int;
export const Account = IDL.Record({
  'pnl' : IDL.Float64,
  'lastUpdated' : Time,
  'icpBalance' : IDL.Float64,
  'cashBalance' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PositionType = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const LeveragedPosition = IDL.Record({
  'leverage' : IDL.Float64,
  'isOpen' : IDL.Bool,
  'positionType' : PositionType,
  'liquidationPrice' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'margin' : IDL.Float64,
  'amountICP' : IDL.Float64,
  'openedAt' : Time,
});
export const Winner = IDL.Record({
  'finalPortfolioValue' : IDL.Float64,
  'winner' : IDL.Principal,
  'profitLoss' : IDL.Float64,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyICP' : IDL.Func([GameMode, IDL.Float64, IDL.Float64], [], []),
  'closePosition' : IDL.Func([GameMode, IDL.Nat, IDL.Float64], [], []),
  'createAccount' : IDL.Func([GameMode], [], []),
  'getAccount' : IDL.Func(
      [GameMode, IDL.Principal],
      [IDL.Opt(Account)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getICPPrice' : IDL.Func([], [IDL.Float64], []),
  'getLeaderboard' : IDL.Func(
      [GameMode],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Account))],
      ['query'],
    ),
  'getOpenPositions' : IDL.Func(
      [GameMode],
      [IDL.Vec(LeveragedPosition)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWinners' : IDL.Func([GameMode], [IDL.Vec(Winner)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWinner' : IDL.Func([GameMode, Winner], [], []),
  'openLongPosition' : IDL.Func(
      [GameMode, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'openShortPosition' : IDL.Func(
      [GameMode, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'resetAccount' : IDL.Func([GameMode], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellICP' : IDL.Func([GameMode, IDL.Float64, IDL.Float64], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Time = IDL.Int;
  const Account = IDL.Record({
    'pnl' : IDL.Float64,
    'lastUpdated' : Time,
    'icpBalance' : IDL.Float64,
    'cashBalance' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PositionType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const LeveragedPosition = IDL.Record({
    'leverage' : IDL.Float64,
    'isOpen' : IDL.Bool,
    'positionType' : PositionType,
    'liquidationPrice' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'margin' : IDL.Float64,
    'amountICP' : IDL.Float64,
    'openedAt' : Time,
  });
  const Winner = IDL.Record({
    'finalPortfolioValue' : IDL.Float64,
    'winner' : IDL.Principal,
    'profitLoss' : IDL.Float64,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyICP' : IDL.Func([GameMode, IDL.Float64, IDL.Float64], [], []),
    'closePosition' : IDL.Func([GameMode, IDL.Nat, IDL.Float64], [], []),
    'createAccount' : IDL.Func([GameMode], [], []),
    'getAccount' : IDL.Func(
        [GameMode, IDL.Principal],
        [IDL.Opt(Account)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getICPPrice' : IDL.Func([], [IDL.Float64], []),
    'getLeaderboard' : IDL.Func(
        [GameMode],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Account))],
        ['query'],
      ),
    'getOpenPositions' : IDL.Func(
        [GameMode],
        [IDL.Vec(LeveragedPosition)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWinners' : IDL.Func([GameMode], [IDL.Vec(Winner)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWinner' : IDL.Func([GameMode, Winner], [], []),
    'openLongPosition' : IDL.Func(
        [GameMode, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'openShortPosition' : IDL.Func(
        [GameMode, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'resetAccount' : IDL.Func([GameMode], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellICP' : IDL.Func([GameMode, IDL.Float64, IDL.Float64], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };