/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'pnl' : number,
  'totalPortfolioValue' : number,
  'lastUpdated' : Time,
  'icpBalance' : number,
  'cashBalance' : number,
  'principalId' : Principal,
}
export interface LedgerTransaction {
  'transactionType' : TransactionType,
  'icpBalanceAfter' : number,
  'timestamp' : Time,
  'price' : number,
  'cashBalanceAfter' : number,
  'icpAmount' : number,
}
export type Time = bigint;
export type TransactionType = { 'buy' : null } |
  { 'sell' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyICP' : ActorMethod<[number], undefined>,
  'getBalance' : ActorMethod<[], [string, number, number]>,
  'getBalanceForUser' : ActorMethod<[Principal], [string, number, number]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getICPPrice' : ActorMethod<[], number>,
  'getOrCreateAccount' : ActorMethod<[], Account>,
  'getTransactionHistory' : ActorMethod<[], Array<LedgerTransaction>>,
  'getTransactionHistoryForUser' : ActorMethod<
    [Principal],
    Array<LedgerTransaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeDefaultGameMode' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellICP' : ActorMethod<[number], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];