/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'pnl' : number,
  'lastUpdated' : Time,
  'icpBalance' : number,
  'cashBalance' : number,
}
export type GameMode = { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface LeveragedPosition {
  'leverage' : number,
  'isOpen' : boolean,
  'positionType' : PositionType,
  'liquidationPrice' : number,
  'entryPrice' : number,
  'margin' : number,
  'amountICP' : number,
  'openedAt' : Time,
}
export type PositionType = { 'long' : null } |
  { 'short' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Winner {
  'finalPortfolioValue' : number,
  'winner' : Principal,
  'profitLoss' : number,
  'timestamp' : Time,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyICP' : ActorMethod<[GameMode, number, number], undefined>,
  'closePosition' : ActorMethod<[GameMode, bigint, number], undefined>,
  'createAccount' : ActorMethod<[GameMode], undefined>,
  'getAccount' : ActorMethod<[GameMode, Principal], [] | [Account]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getICPPrice' : ActorMethod<[], number>,
  'getLeaderboard' : ActorMethod<[GameMode], Array<[Principal, Account]>>,
  'getOpenPositions' : ActorMethod<[GameMode], Array<LeveragedPosition>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWinners' : ActorMethod<[GameMode], Array<Winner>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markWinner' : ActorMethod<[GameMode, Winner], undefined>,
  'openLongPosition' : ActorMethod<
    [GameMode, number, number, number],
    undefined
  >,
  'openShortPosition' : ActorMethod<
    [GameMode, number, number, number],
    undefined
  >,
  'resetAccount' : ActorMethod<[GameMode], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellICP' : ActorMethod<[GameMode, number, number], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];